let items = [
    {
        id: 1,
        name: "Kit Kat",
        image: "https://picsum.photos/50/50",
        price: 10,
        discount: 5,
        tax: 18,
        quantity: 5,
        visible: true,
    },
    {
        id: 2,
        name: "Dairy Milk",
        image: "https://picsum.photos/50/50",
        price: 15,
        discount: 5,
        tax: 18,
        quantity: 5,
        visible: true,
    },
    {
        id: 3,
        name: "Juice",
        image: "https://picsum.photos/50/50",
        price: 25,
        discount: 5,
        tax: 18,
        quantity: 5,
        visible: true,
    },
    {
        id: 4,
        name: "Waffle",
        price: 60,
        image: "https://picsum.photos/50/50",
        discount: 5,
        tax: 18,
        quantity: 5,
        visible: true,
    },
    {
        id: 5,
        name: "Biscuit",
        price: 80,
        image: "https://picsum.photos/50/50",
        discount: 5,
        tax: 18,
        quantity: 5,
        visible: true,
    },
];
